/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ComandosLeituraGravaçao;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {

        Scanner leitor = new Scanner(System.in);
        
        int idade = leitor.nextInt();
        
        System.out.println(idade);
        
        float cotacaoDolar = leitor.nextFloat();
        
        double cotacaoEuro = leitor.nextDouble();
        
        String nome = leitor.nextLine(); // lê a frase inteira
        
        String codigoRua = leitor.next(); // lê apenas uma palavra
        
        System.out.println("Texto que será exibido no console");
        
        System.out.print("Texto que será exibido no console");
        
    }
}
